### ISSUE TITLE
Not getting 100% accuracy for W4

### ISSUE THREAD

**Issue by matinciel** [DanielCCF/BotGamesAA#1]
Hello,

hope it's the right way to contact you ! If not sorry :)

First very nice code for week 4 ! (I did it too using pyTesseract, but with a lot of copy/paste...).

Your code is way faster, 7second vs 20 for mine (not using DOM).

I feel exactly the same as you (in the read me) concerning week 4 👍 

I guess if you want not use regex, Ken has share a nice method using (kind of Regex maybe ?)
`rpa.get_text(stringocrtosearchin,'_text_balise_on the_left','text_balise_on_the_left').`
It working fine with most of the line (except the date), using invoice number and /n.

I have tried an other way creating a "template" for each invoice, only giving Tesseract a crop of what it should read (maybe it's a kind of regex too for you ?).

Now the 'issue' :
I have try to run your code on my PC and can't get 100% accuracy (I get 85.71% - reproduced twice, not tested more with both turbo and non tubro mode).

I have added some print() of the values, I can't see any issue too...

When the program click on submit I see a green mark "correct" (and never see something else).

```
Invoice1.tiff
Number 10266 Date 22 Aug 2018 Total 1064.92 Quant ['15', '15', '15'] desc ['Sprocket - Large', 'Sprocket - Med', 'Sprocket - Small'] tot per item ['577.50', '284.25', '133.50']
Invoice10.tiff
Number 10291 Date 22 Aug 2018 Total 3967.03 Quant ['100', '150', '200', '100'] desc ['Tylenol Ex-Strong 100/box', 'NGK-ZFR5F-11 Spark Plug', 'Radiator coolant', 'Snow White Paint'] tot per item ['1495.00', '412.50', '1000.00', '800.00']
Invoice2.tiff
Number 10267 Date 22 Aug 2018 Total 1198.40 Quant ['25', '25', '25'] desc ['Bracket - Widget Type A', 'Bracket - Widget Type C', 'Bracket - Widget Type B'] tot per item ['181.25', '918.75', '20.00']
Invoice3.tiff
Number 10268 Date 22 Aug 2018 Total 5633.55 Quant ['50', '50', '50'] desc ['Widget Type A', 'Bracket - Widget Type B', 'Widget Type C'] tot per item ['1100.00', '40.00', '4125.00']
Invoice4.tiff
Number 10269 Date 22 Aug 2018 Total 754.35 Quant ['12', '12'] desc ['Widget Type A', 'Bracket - Widget Type C'] tot per item ['264.00', '441.00']
Invoice8.tiff
Number 10292 Date 22 Aug 2018 Total 1361.58 Quant ['50', '100', '50'] desc ['Tylenol Ex-Strong 100/box', 'NGK-ZFR5F-11 Spark Plug', 'Radiator coolant'] tot per item ['747.50', '275.00', '250.00']
Invoice9.tiff
Number 10289 Date 22 Aug 2018 Total 12686.19 Quant ['175', '175', '175'] desc ['Widget Type A', 'Sprocket - Large', 'Bracket - Widget Type A'] tot per item ['3850.00', '6737.50', '1268.75']
```

In my code I get a weird behaviour for Tessaract which adds only for the last invoice (invoice10.tiif, not processed in the same order in Windows) a non utf-8 character in the text, and have to precise the encoding to solve it (but as I don't see any issue ).

If you have any idea (if not no need to look for it) ?

Again thanks for sharing that code !

**Comment by matinciel** [comment]
Update someone confirms he was able to go for 100% accuracy on this thread, so probably my environnement (and skills).
https://community.aisingapore.org/groups/tagui-rpa/forum/discussion/rpa-challenge-submissions/page/2/

**Comment by DanielCCF** [comment]
Hi @matinciel ! 

No worries, you can contact me here too. Thanks for sharing this method that Ken pointed!

And yeah, OCR/AI is like a new world for me, which I scratched the surface sometimes. I thought about cropping the images to help the Tesseract, but I didn't find a way to do this systematically, that is why I used REGEX.

I'm in doubt about what is happening about your issue. I think is something related to the Tessaract or the characters configuration/keyboard of your PC.

To figure out this issue, I'd use this website: [https://regex101.com/](https://regex101.com/), with the configuration set to Python and the invoice 10 information from the raw output of your Tesseract. 

I did use this site by grabbing all the outputs from tesseract and testing the REGEX queries. The same group of queries was able to extract the information on most of the occasions, besides the 'Invoice no.'. In this case, the  query for the invoice number is like this:

Invoice no. 11111

Is different when it happens on the next line:

Some information Invoice no. 
22 More information 11111

If the queries work with you on this website, it means it should be something related to the keyboard configuration, maybe how Python chooses the formatting too.

This is only a guess and how I would debug it. I'd not be surprised if something different than this.

**Comment by matinciel** [comment]
Thanks for the website ! I will not test further :)

**Comment by DanielCCF** [comment]
You're welcome :)

I'll be closing the issue, but we can talk about this at any moment if you need to.

Have a great week!
